name = "status-blackroad"
main = "src/worker.js"
compatibility_date = "2024-12-01"
workers_dev = true

routes = [
  { pattern = "status.blackroad.io/*", zone_name = "blackroad.io" }
]

[triggers]
crons = ["*/5 * * * *"]

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "STATUS_KV"
id = "226c06fbcb5a4993b0481f85ee2e527a"
