name = "backroad-social"
main = "src/worker.js"
compatibility_date = "2024-09-01"
workers_dev = true

routes = [
  { pattern = "backroad.blackroad.io/*", zone_name = "blackroad.io" },
  { pattern = "social.blackroad.io/*", zone_name = "blackroad.io" },
]

[[d1_databases]]
binding = "DB"
database_name = "backroad-social"
database_id = "bf074bed-fa02-40b9-af74-789255c961f7"

[ai]
binding = "AI"
