name = "road-search"
main = "src/worker.js"
compatibility_date = "2024-09-01"

[[d1_databases]]
binding = "DB"
database_name = "road-search"
database_id = "cfd5c94b-6742-4daf-ac13-59c859be3a8f"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "CACHE"
id = "c878fbcc1faf4eddbc98dcfd7485048d"

[vars]
OLLAMA_URL = "https://ollama.blackroad.io"
STATS_API = "https://stats-blackroad.amundsonalexa.workers.dev"
